import es_users
print "A"
a, users_with_status_coordinates = es_users.getAllUsers_WithCoordinates()
print "B"
b, users_with_status_coordinates = es_users.getAllUsers_WithTweets_WithCoordinates(users_with_status_coordinates)
print "C"
c, users_with_status_coordinates, not_found_places = es_users.getAllUsers_WithTweets_WithPlaces_WithoutCoordinates(users_with_status_coordinates)
print "D"
d, users_with_status_coordinates, not_found_places = es_users.getAllUsers_WithTweets_WithLocation_WithoutCoordinates_and_WithoutPlaces(users_with_status_coordinates)
print "E"
e, users_with_status_coordinates = es_users.getAllUsers_WithTweets_WithOutLocation_WithoutCoordinates_and_WithoutPlaces(users_with_status_coordinates)
